apps/membership/urls.py
# urls.py
from django.urls import path

from .views import (
    ClubAdmin,
    CreateOrganizationView,
    DeleteOrganizationView,
    JoinOrganizationView,
    OrganizationAdmin,
    OrganizationDetailView,
    ClubListView,
    UpdateOrganizationView,
    PromoterListView,
    JoinClubView,
    LeaveClubView,
    PromoteMemberView,
    ExportCSV

)

app_name = "membership"

urlpatterns = [
    path("org", ClubListView.as_view(), name="organizations"),
    path("promoters", PromoterListView.as_view(), name="promoters"),
    path("org/create/", CreateOrganizationView.as_view(), name="create_organization"),
    path("org/admin/<int:pk>/", OrganizationAdmin.as_view(), name="organization_admin"),
    path("org/<int:pk>/", OrganizationDetailView.as_view(), name="organization_detail"),
    path("org/<int:pk>/update/", UpdateOrganizationView.as_view(), name="update_organization"),
    path("org/<int:pk>/delete/", DeleteOrganizationView.as_view(), name="delete_organization"),
    path("org/join", JoinOrganizationView.as_view(), name="join_organization"),
    path("org/join/<int:pk>/", JoinClubView.as_view(), name="join_club"),
    path("org/leave/<int:pk>/", LeaveClubView.as_view(), name="leave_club"),
    path("org/join/<int:organization_id>/", JoinOrganizationView.as_view(), name="join_organization_from_details"),
    path("org/clubs_admin/", ClubAdmin.as_view(), name="clubs_admin"),
    path('org/<int:pk>/promote/<int:member_id>/', PromoteMemberView.as_view(), name='promote_member'),
    path('org/<int:pk>/export_csv/', ExportCSV.as_view(), name='export_csv'),
]

config/urls.py
from datetime import date

from allauth.account.views import SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from apps.event.models import Event
from events.users.forms import UserSignupForm


class HomePageView(TemplateView):
    """This view loads if the user is logged in"""

    template_name = "pages/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #  Feature event
        context["featured_events"] = Event.objects.all().filter(
            Q(logo__isnull=False) & ~Q(logo="") & Q(featured_event=True) & Q(end_date__gte=date.today())
        )[:6]
        # print(f"featured list: {[(i.name, i.logo) for i in context['featured_events']]}")
        return context


class HomePageSignUpView(SignupView):
    """This view loads if you are not logged in"""

    template_name = "pages/home.html"  # your custom template
    form_class = UserSignupForm  # your custom form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #  Feature event
        context["featured_events"] = Event.objects.all().filter(
            Q(logo__isnull=False) & ~Q(logo="") & Q(featured_event=True) & Q(end_date__gte=date.today())
        )[:6]
        # print(f"featured list: {[(i.name, i.logo) for i in context['featured_events']]}")
        return context

    def form_valid(self, form):
        # Here we can add our custom logic for login
        parent_email = form.cleaned_data.get("parent_email")
        parent_name = form.cleaned_data.get("parent_name")
        render_to_string(
            "emails/new_account_parent_notifcation.html",
            {
                "parent_name": parent_name,
            },
        )
        send_mail(
            "Your child has created an account at Bicycle Colorado"
            f"Hello {parent_name},\n\nYour child has created an account at Bicycle Colorado\n "
            f"https://events.bicyclecolorado.org",
            "info@bicyclecolorado.org",
            [parent_email],
            fail_silently=False,
        )
        # Don't forget to call super
        return super().form_valid(form)

    def form_invalid(self, form):
        # Here you can handle the form errors
        return render(self.request, self.template_name, {"form": form})


if "events.bicycecolorado.org" in settings.ALLOWED_HOSTS:
    robots = "prod_robots.txt"
else:
    robots = "dev_robots.txt"

urlpatterns = [
    path("", HomePageSignUpView.as_view(), name="home"),
    path("home", HomePageView.as_view(), name="homepage"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("events.users.urls", namespace="users")),
    # Accounts
    path("accounts/", include("allauth.urls")),
    # Apps
    path("", include("apps.event.urls")),
    path("", include("apps.membership.urls")),
    path("", include("apps.usac.urls")),
    path("", include("apps.store.urls")),
    path("", include("apps.setup.urls")),
    # Your stuff: custom urls includes go here
    path(
        "robots.txt",
        TemplateView.as_view(template_name=robots, content_type="text/plain"),
        name="robots",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/membership/models.py
"""
Not migrating
- class OrganizationMemberOrg(models.Model):
"""
from datetime import timedelta
from pathlib import Path

from cerberus import Validator
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
# from jsonschema import Validator TODO: what is this?
from phonenumber_field.modelfields import PhoneNumberField
from simple_history.models import HistoricalRecords

from ..usac.models import UsacDownload

User = get_user_model()


def organization_logo_file_path_func(instance, filename):
    from events.helpers import get_random_upload_path

    return get_random_upload_path(str(Path("uploads", "cycling_org", "organization", "logo")), filename)


def organization_hero_file_path_func(instance, filename):
    from events.helpers import get_random_upload_path

    return get_random_upload_path(str(Path("uploads", "cycling_org", "organization", "hero")), filename)


class OrganizationMember(models.Model):
    """
    organization: key to Organization the member record is for.
    member: key to Member the member record is for.
    is_admin: the Member is an admin of the Organization.
    is_master_admin: TODO: Removed
    membership_price: TODO: Removed
    membership_plan: TODO: Removed
    is_active: The member has a active/current membership, not expired. There is a background script that updates this
        from the expiration date. Admins are always active.
    org_member_uid: TODO: I dont think we need this.
    start_date: Join date, This is the date of first join.
    exp_date: Default is members are renewed evenry calendar year. Jan 1 - Dec 31
    member_fields: custom field the Org defines for the member. This is a JSONField. TODO: Removed
    status = models.CharField(max_length=16, null=True, choices=STATUS_CHOICES) TODO: removed
    datetime = models.DateTimeField(auto_now_add=True)
    history: tacks changes to the record
    """

    organization = models.ForeignKey("Organization", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True, null=True)
    start_date = models.DateField(null=True)
    exp_date = models.DateField(null=True)
    datetime = models.DateTimeField(auto_now_add=True)
    history = HistoricalRecords()

    class Meta:
        unique_together = [["organization", "user"]]

    def is_expired(self):
        if not self.exp_date:
            return False
        return timezone.now().date() > self.exp_date

    def is_expiring(self, days=5):
        if not self.exp_date:
            return False
        return timezone.now().date() >= (self.exp_date - timedelta(days=days))

    def save(self, *args, **kwargs):
        if not self.is_active:
            self.is_active = None
        return super().save(*args, **kwargs)

    def is_org_admin(self, *args, **kwargs):
        a = self.organization.organizationmember_set.filter(user=self.kwargs.user, is_admin=True).exists()
        return a or self.kwargs.user.is_staff

    def __str__(self):
        return (
            f"{self.organization} - {self.user} - {self.is_admin} - {self.is_active} - {self.start_date} - "
            f"{self.exp_date}"
        )


class Organization(models.Model):
    """
    name: Name of the organization
    type: Club, Promoter, advocacy_volunteer. This effects some views.
    social_media: Social media links
    website: URL to the website, facebook, ...
    phone = PhoneNumberField(max_length=50, null=True, blank=True)
    phone_verified: Verify so that we can send sms messages. TODO: Removed
    email: Email address
    email_verified: We don't need to implement verification now. TODO: removed
    address: Street address
    country: Country, default USA
    city: City
    state: State default Colorado
    zipcode: Zipcode
    about: Short unformated text.
    details: Long formated text. TODO: New field, form prefs.information_board_content
    logo: Small image
    hero: larger banner, hero image TODO: New field, form prefs.banner_image, dont need to migrate
    signup_config: TODO: removed
    membership_plans: TODO: removed
    member_fields_schema: TODO: removed
    verified = models.BooleanField(default=False) TODO: removed
    prefs = models.JSONField(null=True, blank=True, editable=True)
    - banner_image: TODO: Use hero, don't need to migrate, user can update later
    - information_board_content: TODO: move to details, Dont need to migrate, user can update later.
    user = models.ManyToManyField(User, related_name='organizations', through=OrganizationMember)
    member_orgs: TODO: removed
    membership_open: True, False, if allowing new members
    approved: New orgs must be approved by BC is_staff
    rss_url: TODO: removed
    waiver_text: This is shown on the join org page and useer must agree to it.
    _tracker: TODO, removed
    """

    SOCIAL_MEDIA_SCHEMA = {
        "youtube": {"type": "string", "required": False, "nullable": True, "meta": {"title": "Youtube"}},
        "facebook": {"type": "string", "required": False, "nullable": True, "meta": {"title": "Facebook"}},
        "instagram": {"type": "string", "required": False, "nullable": True, "meta": {"title": "Instagram"}},
    }
    TYPE_REGIONAL = "regional"
    TYPE_CLUB = "club"
    TYPE_ADVOCACY_VOLUNTEER = "advocacy_volunteer"
    TYPE_PHOTOGRAPHER = "photographer"
    TYPE_PROMOTER = "promoter"
    TYPE_CHOICES = (
        (TYPE_REGIONAL, "Regional"),
        (TYPE_CLUB, "Club"),
        (TYPE_ADVOCACY_VOLUNTEER, "Advocacy, Volunteer"),
        (TYPE_PHOTOGRAPHER, "Photographer"),
        (TYPE_PROMOTER, "Promoter"),
    )
    name = models.CharField(max_length=256, unique=True)
    type = models.CharField(max_length=32, choices=TYPE_CHOICES)
    blurb = models.TextField(max_length=500, blank=True)
    description = models.TextField(blank=True)
    social_media = models.JSONField(null=True, blank=True)
    website = models.URLField(blank=True)
    phone = PhoneNumberField(max_length=50, null=True, blank=True)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=256, blank=True)
    country = models.CharField(max_length=128, blank=True, default="USA")
    city = models.CharField(max_length=128, blank=True)
    state = models.CharField(max_length=128, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    logo = models.ImageField(null=True, blank=True, max_length=500, upload_to=organization_logo_file_path_func)
    hero = models.ImageField(null=True, blank=True, max_length=500, upload_to=organization_hero_file_path_func)
    user = models.ManyToManyField(User, related_name="organizations", through=OrganizationMember)
    membership_open = models.BooleanField(default=False, null=True, blank=True)
    approved = models.BooleanField(default=False, null=True)  # New orgs must be approved by BC staff
    waiver_text = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        if self.email:
            self.email = self.email.lower()
        if self.social_media:
            v = Validator(self.SOCIAL_MEDIA_SCHEMA, allow_unknown=True)
            if not v.validate(self.social_media):
                raise ValidationError({"social_media": str(v.errors)})
            self.social_media = v.document
        else:
            self.social_media = {}
        return super().save(*args, **kwargs)

    @property
    def is_usac(self):
        return UsacDownload.objects.filter(data__club=self.name).exists()

    @property
    def usac_members(self):
        return UsacDownload.objects.filter(data__club=self.name)

    @property
    def bc_members(self):
        return OrganizationMember.objects.filter(organization=self.id)

    def __str__(self):
        return f"{self.name}"

apps/membership/templates/forms/organization_form.html
{% load static %}
{% load widget_tweaks %}

<!-- Form body -->
<form method="post" id="organization_form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="grid gap-4 mb-4 sm:grid-cols-2">

    <!-- Org Name -->
    <div>
      <label for="{{ form.name.auto_id }}" class="fb_text_label">{{ form.name.label }}</label>
      {{ form.name }}
      {% if form.name.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.name.errors }}</div>
      {% endif %}
    </div>

    <!-- Org Website -->
    <div>
      <label for="{{ form.website.auto_id }}" class="fb_text_label">{{ form.website.label }}</label>
      {{ form.website }}
      {% if form.website.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.website.errors }}</div>
      {% endif %}
    </div>

    <!-- Phone -->
    <div>
      <label for="{{ form.phone.auto_id }}"
             class="fb_text_label">{{ form.phone.label }}</label>
      {{ form.phone }}
      {% if form.phone.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.phone.errors }}</div>
      {% endif %}
    </div>

    <!-- Org Email -->
    <div>
      <label for="{{ form.email.auto_id }}" class="fb_text_label">{{ form.email.label }}</label>
      {{ form.email }}
      {% if form.email.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.email.errors }}</div>
      {% endif %}
    </div>

    <!-- Address -->
    <div>
      <label for="{{ form.is_permitted.auto_id }}"
             class="fb_text_label ml-2">{{ form.address.label }}</label>
      {{ form.address }}
      {% if form.address.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.address.errors }}</div>
      {% endif %}
    </div>

    <!-- Org City -->
    <div>
      <label class="fb_text_label" for="{{ form.city.auto_id }}">{{ form.city.label }}</label>
      {{ form.city }}
      {% if form.city.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.city.errors }}</div>
      {% endif %}
    </div>

    <!-- Org State -->
    <div>
      <label for="{{ form.state.auto_id }}" class="fb_text_label">{{ form.state.label }}</label>
      {{ form.state }}
      {% if form.state.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.state.errors }}</div>
      {% endif %}
    </div>

    <!-- Org zipcode -->
    <div>
      <label for="{{ form.zipcode.auto_id }}" class="fb_text_label">{{ form.zipcode.label }}</label>
      {{ form.zipcode }}
      {% if form.zipcode.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.zipcode.errors }}</div>
      {% endif %}
    </div>

    <!-- Org Logo -->
    <div class="sm:col-span-2">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
             for="{{ form.logo.id_for_label }}">
        {{ form.logo.label }}
      </label>
      <div class="sm:col-span-2">
        <div class="items-center w-full sm:flex">
          <div class="w-full">
            {{ form.logo }}
            <p class="mt-1 text-xs font-normal text-gray-500 dark:text-gray-300" id="file_input_help">SVG, PNG,
              Suggested size (250x250px)</p>
          </div>
        </div>
      </div>
      {% if form.logo.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.logo.errors }}</div>
      {% endif %}
    </div>

    <!-- Org Hero -->
    <div class="sm:col-span-2">
      <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
             for="{{ form.hero.id_for_label }}">
        {{ form.hero.label }}
      </label>
      <div class="sm:col-span-2">
        <div class="items-center w-full sm:flex">
          <div class="w-full">
            {{ form.hero }}
            <p class="mt-1 text-xs font-normal text-gray-500 dark:text-gray-300" id="file_input_help">SVG, PNG,
              Suggested size (1920X1080)</p>
          </div>
        </div>
      </div>
      {% if form.hero.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.hero.errors }}</div>
      {% endif %}
    </div>

    <!-- Blurb -->
    <div class="sm:col-span-2">
      <label for="{{ form.blurb.auto_id }}" class="fb_text_label">{{ form.blurb.label }}</label>
      {{ form.blurb }}
      {% if form.blurb.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.blurb.errors }}</div>
      {% endif %}
    </div>

    <!-- Description -->
    <div class="sm:col-span-2">
      <label for="{{ form.description.auto_id }}"
             class="fb_text_label">{{ form.description.label }}</label>
      {{ form.description }}
      <div>
        {% if form.description.errors %}
          <div class="text-red-500 text-xs mt-1">{{ form.description.errors }}</div>
        {% endif %}
      </div>
    </div>

    <!-- Waiver text -->
    <div class="sm:col-span-2">
      <label for="{{ form.waiver_text.auto_id }}"
             class="fb_text_label">{{ form.waiver_text.label }}</label>
      {{ form.waiver_text }}
      <div>
        {% if form.waiver_text.errors %}
          <div class="text-red-500 text-xs mt-1">{{ form.waiver_text.errors }}</div>
        {% endif %}
      </div>
    </div>

    <!-- membership_open -->
    <div class="flex items-center">
      {{ form.membership_open }}
      <label for="{{ form.membership_open.auto_id }}"
             class="fb_text_label ml-2">{{ form.membership_open.label }}</label>
      {% if form.membership_open.errors %}
        <div class="text-red-500 text-xs mt-1">{{ form.membership_open.errors }}</div>
      {% endif %}
    </div>
  </div>

  <!-- End of fields, start of buttons -->
  <div class="items-center">
    <button type="submit"
            class="w-full justify-center sm:w-auto text-white  button_body_cyan">
      <i class="fa-solid fa-square-check mr-1"></i>Create Club
    </button>
  </div>
  <div>{% if form.errors %} Form Errors are {{ form.errors }} {% endif %}</div>
</form>

<script>
  tinymce.init({
    selector: "textarea#id_description",
    height: 500,
    menubar: false,
    plugins: ['link', 'image', 'media', 'lists', 'table'],
    toolbar: "undo redo | bold | italic | link | alignleft aligncenter alignright alignjustify | outdent indent | removeformat | image | media | numlist bullist",
    content_style: "body { font-family:Helvetica,Arial,sans-serif; font-size:14px }"
  });

  tinymce.init({
    selector: "textarea#id_waiver_text",
    height: 500,
    menubar: false,
    plugins: ['link'],
    toolbar: "undo redo | bold italic link | alignleft aligncenter alignright alignjustify | outdent indent | removeformat",
    content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
  });
  document.getElementById('organization_form').addEventListener('submit', function (e) {
    tinymce.triggerSave();  // Save content from TinyMCE back to textarea
    const descriptionContent = document.getElementById('id_description').value.trim();
    if (!descriptionContent) {
      e.preventDefault();
      alert('Description is required');
    }
    const waiverContent = document.getElementById('id_waiver_text').value.trim();
    if (!waiverContent) {
      e.preventDefault();
      alert('Waiver is required');
    }
  });
</script>