apps/event/urls.py
from django.urls import path

from .views import (
    EventCreateView,
    EventDeleteView,
    EventDetailView,
    EventListView,
    EventResultListView,
    EventUpdateView,
    RaceCreateView,
    RaceResultCreateView,
    RaceResultsImportView,
    RaceSeriesCreateView,
    RaceSeriesDetailView,
    RaceSeriesUpdateView,
    EventsWaitingApproval,
)

app_name = "event"

urlpatterns = [
    path("events/", EventListView.as_view(), name="event_list"),
    path("events/create/", EventCreateView.as_view(), name="event_create"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event_detail"),
    path("events/<int:pk>/update/", EventUpdateView.as_view(), name="event_update"),
    path("events/<int:pk>/delete/", EventDeleteView.as_view(), name="event_delete"),
    path("events/upload_results/<int:event_pk>", RaceResultsImportView, name="import_race_results"),
    path("events/results/", EventResultListView.as_view(), name="events_results_list"),
    path("raceseries/<int:pk>", RaceSeriesDetailView.as_view(), name="raceseries_detail"),
    path("raceseries/create/", RaceSeriesCreateView.as_view(), name="raceseries_create"),
    path("raceseries/<int:pk>/update/", RaceSeriesUpdateView.as_view(), name="raceseries_update"),
    path("race/create/", RaceCreateView.as_view(), name="race_create"),
    path("raceresult/create/", RaceResultCreateView.as_view(), name="raceresult_create"),
    path("events/approval/", EventsWaitingApproval.as_view(), name="events_waiting_approval"),
]

config/urls.py
from datetime import date

from allauth.account.views import SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from apps.event.models import Event
from events.users.forms import UserSignupForm


class HomePageView(TemplateView):
    """This view loads if the user is logged in"""

    template_name = "pages/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #  Feature event
        context["featured_events"] = Event.objects.all().filter(
            Q(logo__isnull=False) & ~Q(logo="") & Q(featured_event=True) & Q(end_date__gte=date.today())
        )[:6]
        # print(f"featured list: {[(i.name, i.logo) for i in context['featured_events']]}")
        return context


class HomePageSignUpView(SignupView):
    """This view loads if you are not logged in"""

    template_name = "pages/home.html"  # your custom template
    form_class = UserSignupForm  # your custom form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #  Feature event
        context["featured_events"] = Event.objects.all().filter(
            Q(logo__isnull=False) & ~Q(logo="") & Q(featured_event=True) & Q(end_date__gte=date.today())
        )[:6]
        # print(f"featured list: {[(i.name, i.logo) for i in context['featured_events']]}")
        return context

    def form_valid(self, form):
        # Here we can add our custom logic for login
        parent_email = form.cleaned_data.get("parent_email")
        parent_name = form.cleaned_data.get("parent_name")
        render_to_string(
            "emails/new_account_parent_notifcation.html",
            {
                "parent_name": parent_name,
            },
        )
        send_mail(
            "Your child has created an account at Bicycle Colorado"
            f"Hello {parent_name},\n\nYour child has created an account at Bicycle Colorado\n "
            f"https://events.bicyclecolorado.org",
            "info@bicyclecolorado.org",
            [parent_email],
            fail_silently=False,
        )
        # Don't forget to call super
        return super().form_valid(form)

    def form_invalid(self, form):
        # Here you can handle the form errors
        return render(self.request, self.template_name, {"form": form})


if "events.bicycecolorado.org" in settings.ALLOWED_HOSTS:
    robots = "prod_robots.txt"
else:
    robots = "dev_robots.txt"

urlpatterns = [
    path("", HomePageSignUpView.as_view(), name="home"),
    path("home", HomePageView.as_view(), name="homepage"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("events.users.urls", namespace="users")),
    # Accounts
    path("accounts/", include("allauth.urls")),
    # Apps
    path("", include("apps.event.urls")),
    path("", include("apps.membership.urls")),
    path("", include("apps.usac.urls")),
    path("", include("apps.store.urls")),
    path("", include("apps.setup.urls")),
    # Your stuff: custom urls includes go here
    path(
        "robots.txt",
        TemplateView.as_view(template_name=robots, content_type="text/plain"),
        name="robots",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

events/users/urls.py
from django.urls import path

from events.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)
from events.users.views_emails import EmailsView

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("emails/", view=EmailsView.as_view(), name="emails"),
]

apps/event/views.py
from datetime import date

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Exists, OuterRef, Q
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, FormView

from events.users.permission_utils import is_org_admin, StaffRequiredMixin
from events.utils.events_utils import sys_send_mail
from .forms import (
    RaceForm,
    RaceResultForm,
    RaceResultsImport,
    RaceSeriesForm,
    EventStaffForm,
    EventOrgAdminForm,
    EventAuthenticatedUserForm,
    EventCommunityForm,
)
from .models import Event, Race, RaceResult, RaceSeries
from .validators import ImportResults
from ..membership.models import OrganizationMember, Organization

User = get_user_model()


class EventListView(ListView):
    model = Event
    template_name = "event/event_list.html"
    context_object_name = "events"
    paginate_by = 25
    ordering = ["end_date"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Champion Events
        context["champions"] = Event.objects.all().filter(
            Q(champion_event=True) & Q(end_date__gte=date.today()) & Q(approved=True)
        )
        #  Feature event
        context["featured"] = Event.objects.all().filter(Q(featured_event=True) & Q(approved=True))[:8]
        context["filtered"] = bool(self.request.GET)

        # Get page_obj from context
        page_obj = context.get("page_obj", None)
        if page_obj is not None:
            # We will show page numbers for 3 pages on each side of the current page
            start_page = max(page_obj.number - 3, 1)
            end_page = min(page_obj.number + 3, page_obj.paginator.num_pages)

            # Create list of page numbers
            page_range = list(range(start_page, end_page + 1))
            context["custom_page_range"] = page_range

        context["total_count"] = self.get_queryset().count()
        withpage = self.request.GET.copy()
        withpage.pop("page", None)
        context["withpage"] = "&" + withpage.urlencode() if withpage else ""
        return context

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        if "past_events" not in self.request.GET:
            queryset = queryset.filter(Q(end_date__gte=date.today()) & Q(approved=True))
        else:
            queryset = queryset.filter(Q(start_date__lte=date.today()) & Q(approved=True))
        search_query = self.request.GET.get("search", "")
        filter_usac = self.request.GET.get("filter_usac", "")
        filter_featured = self.request.GET.get("filter_featured", "")
        if any([search_query, filter_usac, filter_featured]):
            if search_query:
                queryset = queryset & queryset.filter(
                    Q(name__icontains=search_query)
                    | Q(website__icontains=search_query)
                    | Q(city__icontains=search_query)
                    | Q(state__icontains=search_query)
                )
            if filter_usac:
                queryset = queryset & queryset.filter(is_usac_permitted=True)
            if filter_featured:
                queryset = queryset & queryset.filter(featured_event=True)
        return queryset


class EventsWaitingApproval(StaffRequiredMixin, LoginRequiredMixin, ListView):
    model = Event
    template_name = "event/events_waiting_approval.html"
    context_object_name = "events"
    ordering = ["start_date"]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(approved=False)

        search_term = self.request.GET.get('search_term')
        if search_term:
            queryset = queryset.filter(name__icontains=search_term)

        return queryset

    def post(self, request, *args, **kwargs):
        event_ids = request.POST.getlist('event_ids')
        if event_ids:
            Event.objects.filter(id__in=event_ids).update(approved=True)
        return redirect(reverse('event:events_waiting_approval'))  # Redirect back to the same page after approval

class EventResultListView(ListView):
    model = Event
    template_name = "results/events_results_list.html"
    context_object_name = "events"

    # paginate_by = 10  # Change this to the desired number of items per page
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["RaceSeries"] = RaceSeries.objects.all()
        return context

    def get_queryset(self):
        queryset = Event.objects.filter(
            Q(start_date__lte=date.today()) & Q(Exists(Race.objects.filter(event=OuterRef("pk"))))
        ).order_by("-start_date")
        search_query = self.request.GET.get("search", "")
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query)
                | Q(website__icontains=search_query)
                | Q(city__icontains=search_query)
                | Q(state__icontains=search_query)
            )
        return queryset


class EventDetailView(DetailView):
    model = Event
    template_name = "event/event_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["EventAdmin"] = OrganizationMember.objects.filter(
            Q(user=self.request.user.id) & Q(is_admin=True) & Q(organization=self.object.organization)
        )
        context["Races"] = Race.objects.filter(event=context["object"])
        context["RaceResults"] = RaceResult.objects.filter(race__in=context["Races"])
        context["GOOGLE_MAP_API_TOKEN"] = settings.GOOGLE_MAP_API_TOKEN
        return context


class EventCreateView(CreateView):
    model = Event
    template_name = "event/event_create.html"
    success_url = reverse_lazy("event:event_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_anonymous:
            if self.request.user.is_staff:
                context["user_type"] = "EventStaffForm"
            elif is_org_admin(self.request.user):
                context["user_type"] = "EventOrgAdminForm"
            elif self.request.user.is_authenticated:
                context["user_type"] = "EventAuthenticatedUserForm"
        else:
            context["user_type"] = "EventCommunityForm"
        context["GOOGLE_MAP_API_TOKEN"] = settings.GOOGLE_MAP_API_TOKEN
        return context

    def get_form_class(self):
        if not self.request.user.is_anonymous:
            if self.request.user.is_staff:
                return EventStaffForm
            elif is_org_admin(self.request.user):
                return EventOrgAdminForm
            elif self.request.user.is_authenticated:
                return EventAuthenticatedUserForm
        else:
            return EventCommunityForm

    def get_form(self):
        form = super().get_form()
        if "organization" in form.fields:
            if self.request.user.is_staff:
                queryset = Organization.objects.all()
            else:
                queryset = Organization.objects.filter(Q(members__user=self.request.user) & Q(members__is_admin=True))
            form.fields["organization"].queryset = queryset
        return form

    # def form_invalid(self, form):
    #     print("invalide form")
    #     print(form.errors)
    #     return super().form_invalid(form)

    def form_valid(self, form):
        """add unicode for calendar to subject \U0001F4C5"""
        if not self.request.user.is_anonymous:
            user_email = self.request.user.email
            user_name = self.request.user.full_name
        else:
            user_email = form.cleaned_data["user_email"]
            user_name = form.cleaned_data["user_first"] + " " + form.cleaned_data["user_last"]

        html_message = render_to_string(
            "emails/new_event_created_email.html",
            {
                "NAME": user_name,
                "EMAIL": user_email,
                "EVENT_NAME": form.cleaned_data["name"],
            },
        )

        sys_send_mail(
            subject=f"\U0001F4C5 {form.cleaned_data['name']} event submitted for review",
            message="Thanks for submitting an event to Bicycle Colorado. We review each event manually and will let you "
            "know when it is approved.",
            from_email="donotreply@bicyclecolorado.org",
            recipient_list=[user_email],
            recipient_system=settings.CALENDAR_EMAILS,
            html_message=html_message,
            fail_silently=False,
        )
        return super().form_valid(form)


# Update
class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    template_name = "event/event_update.html"
    success_url = reverse_lazy("event:event_list")

    def get_form_class(self):
        if self.request.user.is_staff:
            return EventStaffForm
        elif is_org_admin(self.request.user):
            return EventOrgAdminForm
        else:
            return None

    def get_form(self):
        form = super().get_form()
        if "organization" in form.fields:
            if self.request.user.is_staff:
                queryset = Organization.objects.all()
            else:
                queryset = Organization.objects.filter(Q(members__user=self.request.user) & Q(members__is_admin=True))
            form.fields["organization"].queryset = queryset
        return form


# Delete
class EventDeleteView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Event
    template_name = "event/event_delete.html"
    success_url = reverse_lazy("event_list")
    # TODO: Only is_staff should be able to delete an event

apps/event/templates/event/EditClub.html
{% extends "BC/base_dv.html" %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>Edit Club</title>
</head>
{% block content %}
<section class="content">
  <br />
  <br />
  <br />
  {% if user.is_staff or ClubAdmin %} {% if club.name %}
  <h1>Editing {{ club.name }}</h1>
  {% else %}
  <h1>Create a new Club</h1>
  {% endif %}
  <form style="margin: 20px" method="post" enctype="multipart/form-data">
    {% csrf_token %} {% if not Club.name %}
    <b>Create a new Organization</b>
    <br />
    Choose and Organization type: {{ form.type }} {% else %} Editing
    <b>{{ Club.name }}</b> Organization type: <b>{{ Club.type.upper }}</b>
    <input type="hidden" name="type" value="{{ Club.type }}" />
    {% endif %}

    <ui>
      <li>{{ form.name.label_tag }} {{ form.name }}</li>
      <li>{{ form.about.label_tag }} {{ form.about }}</li>
      <li>{{ form.website.name }} {{ form.website }}</li>
      <li>{{ form.email.name }} {{ form.email }}</li>
      <li>{{ form.phone.name }} {{ form.phone }}</li>
      <li>{{ form.address.name }} {{ form.address }}</li>
      <li>{{ form.city.name }} {{ form.city }}</li>
      <li>{{ form.state.name }} {{ form.state }}</li>
      <li>{{ form.zip.name }} {{ form.zip }}</li>
      <li>{{ form.country.name }} {{ form.country }}</li>
      {# TODO: Description is in a json field. move it to a separate field#}
      <li>{{ form.description.name }} {{ form.description }}</li>
      <li>
        {% if Club.logo.url %} {{ Club.logo.url }}
        <img src="{{ Club.logo.url }}" alt="Logo" width="100" height="100" />
        {% endif %}
        <br />
        {{ form.logo.name }} {{ form.logo }}
      </li>
      {# TODO: Show a preview of the hero image#}
      <li>{{ form.hero.name }} {{ fomr.hero }}</li>
      <li>{{ form.waiver_text.name }} {{ form.waiver_text }}</li>
      TODO: Approved is a hidden field, if the user.is_staff, then Approved,
      otherwise not.
      <li>{{ form.approved.name }} {{ form.approved }}</li>
    </ui>
    <button class="btn btn-primary my-4" type="submit">Submit</button>
  </form>
  {% else %}
  <p>WARNING: You must be logged in and a staff user</p>
  {% endif %}
</section>
{% endblock %}

apps/event/templates/event/JoinClub.html
{% extends "BC/base_dv.html" %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>Join {{ org.name }}</title>
</head>
{% block content %}
<section class="content">
  <br />
  <br />
  <br />
  <form method="post">
    {% csrf_token %}
    <ui>
      <li>You: {{ user.member.first_name }} {{ user.member.last_name }}</li>
      <input type="hidden" name="member" value="{{ user.member.id }}" />
      <li>Are requesting membership in {{ organization }}</li>
      <input type="hidden" name="organization" value="{{ organization }}" />
      <input type="hidden" name="is_active" value="False" />
      <li>
        <textarea class="scrollabletextbox" name="note">
                {{ Club.waiver_text }}
                </textarea
        >
      </li>
      <li><input type="checkbox" name="waiver_accept" value="accept" /></li>
    </ui>
    <br />
    <button class="btn btn-primary my-4" type="submit">
      Join {{ org.name }}
    </button>
  </form>
</section>
{% endblock %}

apps/event/templates/event/event_confirm_delete.html
{% extends "account/base.html" %} {% block inner %}

<h1>Confirm Delete</h1>

<p>Are you sure you want to delete the event "{{ object.name }}"?</p>

<form method="POST" class="space-y-4">
  {% csrf_token %}
  <button
    type="submit"
    class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
  >
    Delete
  </button>
</form>
{% endblock %}

apps/event/templates/event/event_delete.html
{% extends "account/base.html" %}

{% block inner %}
<div class="container mx-auto px-4">
    <h1 class="text-2xl font-bold mb-4">Delete Event</h1>
    <div class="bg-white shadow-lg rounded p-4">
      <p>Are you sure you want to delete "{{ object.name }}"?</p>
    </div>
    <div class="mt-4">
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 text-white py-2 px-4 rounded">Confirm Delete</button>
      </form>
      <a href="{% url 'event:event_list' %}" class="bg-gray-500 text-white py-2 px-4 rounded">Cancel</a>
    </div>
  </div>
{% endblock %}

apps/event/templates/event/event_detail.html
{% extends "account/base.html" %}
{% load static %}
{% block inner %}
  <!-- content -->
  <section id="Event Detail" class="content">
    <!-- event detail -->
    <div class="bg-gray-100 py-10">
      <div class="container mx-auto px-4">
        <div class="grid grid-cols-12 gap-8">
          <!-- Left Side Content -->
          <div class="col-span-8">
            <a href="{% url 'event:event_list' %}" class="text-orange-600 hover:underline">Back To Events</a>
            {% if object.hero %}
              <img
                src="{{ object.hero }}"
                alt="Event Banner" title="" class="object-contain h-500 w-500 justify-center">
            {% endif %}
            {% if object.logo %}
              <img
                src="{{ object.logo.url }}"
                alt="Event Logo" title="" class="object-contain h-250 w-250 justify-start">
            {% endif %}
            <div class="bg-white shadow-lg rounded p-4 mt-4">
              <h2 class="text-2xl font-bold">{{ object.name }}</h2>
              {% if object.blurb %}
                <p>
                  {{ object.blurb }}
                </p>
              {% endif %}


              {% if object.description %}
                <div>
                  {{ object.description |safe }}
                </div>
              {% endif %}

              {% if object.more_data and object.more_data.panels %}
                {% for panel in  object.more_data.panels %}
                  {% if "iframe" in panel.url %}
                    {{ panel.url |safe }}
                  {% else %}
                    <iframe src="{{ panel.url }}" height="350" width="100%"></iframe>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </div>
            <a href="{% url 'event:event_list' %}" class="text-orange-600 mt-4">Back To Events</a>
          </div>

          <!-- Right Side Content -->
          <div class="col-span-4">
            <h3 class="text-xl font-bold text-orange-600 mb-2">Event Details</h3>
            <div class="bg-white shadow-lg rounded p-4">
              <div class="mb-4">
                {% if event.is_usac_permitted %}
                  <img style="max-width:30px" title="USAC Event"
                       src="{% static 'images/USACycling_Logo.svg' %}" alt="usac">
                {% endif %}
                {% if event.featured_event %}
                  <img style="max-width:30px" title="Featured Event"
                       src="{% static 'images/bc-icon.png' %}" alt="Featured Event"/>
                {% endif %}
              </div>
              <h5 class="py-1">{{ object.start_date }} - {{ object.end_date }}</h5>
              <h5 class="py-1"><span>
                            {% if object.city %} {{ object.city }}, {% endif %}
                {% if object.state %} {{ object.state }}{% endif %}
                        </span></h5>
              <h5 class="py-1 text-cyan-600"><span>{% for t in object.tags %}{{ t }}, {% endfor %}</span></h5>
            </div>
            <div class="bg-white shadow-lg rounded p-4 mt-4">
              {% if object.website %}
                <a href="{{ object.website }}"
                   class="mx-8 bg-cyan-600 hover:bg-cyan-800 text-white py-2 px-4 rounded block mt-4 text-center"
                   target="_blank"
                >Event Website</a>
              {% endif %}
              {% if object.registration_website %}
                <a href="{{ object.registration_website }}"
                   class="mx-8 bg-orange-600 hover:bg-orange-800 text-white py-2 px-4 rounded block mt-4 text-center"
                   target="_blank"
                >Registration</a>
              {% endif %}
              {% if object.location_lat and object.location_lon %}
                </div>
                <div class="event-map mt-4">
                  <iframe frameborder="0" style="border:0;width:100%;height:300px;"
                          src="https://www.google.com/maps/embed/v1/place?key={{ GOOGLE_MAP_API_TOKEN }}&q=
                        {{ object.location_lat }} , {{ object.location_lon }} &zoom=16"
                          allowfullscreen></iframe>
                </div>
              {% endif %}
            <div class="bg-white shadow-lg rounded p-4 mt-4">
              <h4>Event Files</h4>
              {% if object.attachments.count >= 1 %}
                {% for attachment in object.attachments.all %}
                  <a target="_blank" href="{{ attachment.file.url }}">{{ attachment.file_name }}</a>
                {% endfor %}
              {% else %}
                <p>No Files</p>
              {% endif %}
            </div>
            <!-- Only Event admin and is_staff sees this -->
            {% if EventAdmin or user.is_staff %}
              <div class="bg-white shadow-lg rounded p-4 mt-4">
                <h4>Event Admin</h4>
                <a
                  href="{% url 'event:event_update' object.pk %}"
                  class="mx-8 bg-orange-600 hover:bg-orange-800 text-white py-2 px-4 rounded block mt-4 text-center"
                  target="_blank"
                >Edit Event</a>
                <a
                  href="{% url 'event:import_race_results' object.pk %}"
                  class="mx-8 bg-cyan-600 hover:bg-cyan-800 text-white py-2 px-4 rounded block mt-4 text-center"
                  target="_blank"
                >Upload Results</a>
              </div>
            {% endif %}
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </section>
  </section id="RaceResults" class="content">
  <div class="bg-white shadow-lg rounded p-4 mt-4">
    {% if Races %}
      {% include 'results/race_result.html' %}
    {% else %}
      <h3> No race results for this event </h3>
    {% endif %}
  </div>

{% endblock %}

apps/event/templates/event/event_list.html
{% extends "base.html" %}
{% load static i18n %}
{% load extra_tags %}
{% block content %}
  <!--- into section -->
  {% include 'components/intro_event_list.html' %}
  {% if not filtered %}
    {% include "components/featured_list.html" %}
  {% endif %}
  {% include "components/event_list_comp.html" %}

{% endblock %}

apps/event/templates/event/events_waiting_approval.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}

  <div id="notificationDiv" class="hidden fixed top-4 right-4 bg-green-500 text-white p-3 rounded-md shadow-md">
    Events approved successfully!
  </div>

  <div class="container mx-auto px-4">

    <!-- Search Form -->
    <div class="mb-4 flex flex-col md:flex-row items-center">
      <form method="get" class="md:flex-grow md:flex items-center mb-4 md:mb-0">
        <input type="text" name="search_term" class="border p-2 rounded-md flex-grow mr-2"
               placeholder="Search for events..." value="{{ request.GET.search_term|default:'' }}">
        <button type="submit" class="submit_search">Search</button>
      </form>
    </div>

    <form method="post">
      {% csrf_token %}
      <button type="submit" class="button_body_cyan">
        <span id="selectedCount">0</span> Approve Selected
      </button>

      <!-- Table Section -->
      <section class="bg-gray-50 p-3 sm:p-5 rounded-lg shadow-md">
        <div class="overflow-x-auto">
          <table class="min-w-full bg-white border">
            <thead class="border-b">
            <tr>
              <th scope="col" class="px-4 py-3">
                <input type="checkbox" id="selectAllCheckbox">
              </th>
              <th scope="col" class="px-4 py-3">Event Name</th>
              <th scope="col" class="px-4 py-3">Start Date</th>
              <th scope="col" class="px-4 py-3">Promoter or Club</th>
              <th scope="col" class="px-4 py-3">User</th>
              <th scope="col" class="px-4 py-3">Submitted Date</th>
              <th scope="col" class="px-4 py-3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}
              <tr class="border-b">
                <td class="px-4 py-3">
                  <input type="checkbox" name="event_ids" value="{{ event.id }}">
                </td>
                <td class="px-4 py-3">{{ event.name }}</td>
                <td class="px-4 py-3">{{ event.start_date }}</td>
                <td class="px-4 py-3">{{ event.organization.name }}</td>
                <td class="px-4 py-3">
                  {% if event.create_by %}
                    <a href="{% url 'users:detail' event.create_by.pk %}" class="text-blue-500 hover:text-blue-600">
                      {{ event.create_by }}
                    </a>
                  {% else %}
                    Community user
                  {% endif %}
                </td>
                <td class="px-4 py-3">{{ event.create_datetime }}</td>
                <td class="px-4 py-3">
                  <a href="{% url 'event:event_detail' event.pk %}" class="text-blue-500 hover:text-blue-600">View
                    Event</a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </section>

    </form>


  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const checkboxes = document.querySelectorAll("input[name='event_ids']");
      const selectAllCheckbox = document.getElementById("selectAllCheckbox");
      const selectedCountEl = document.getElementById("selectedCount");
      const notificationDiv = document.getElementById("notificationDiv");

      selectAllCheckbox.addEventListener("change", function () {
        checkboxes.forEach(cb => cb.checked = selectAllCheckbox.checked);
        updateSelectedCount();
      });

      checkboxes.forEach(cb => {
        cb.addEventListener("change", updateSelectedCount);
      });

      function updateSelectedCount() {
        const selectedCount = [...checkboxes].filter(cb => cb.checked).length;
        selectedCountEl.textContent = selectedCount;
      }


    });
  </script>
{% endblock %}